import {serve} from "@hono/node-server";
import {Hono} from "hono";
import {ProviderRegistry,CapabilityRouter} from "@mind-z/runtime";
import {BrowserTaskRouter,PlaywrightMcpBackend} from "@mind-z/browser";
import {defaultProviders} from "./providers.js";
const registry=new ProviderRegistry(defaultProviders),router=new CapabilityRouter(registry),browser=new BrowserTaskRouter([new PlaywrightMcpBackend(process.env.PLAYWRIGHT_MCP_URL)]);
const app=new Hono();
app.get("/health",c=>c.json({ok:true,version:"0.4.0"}));
app.get("/providers",c=>c.json({providers:registry.list()}));
app.post("/route",async c=>{const body=await c.req.json<{capability:string;policy?:any}>();return c.json(router.plan({capability:body.capability,policy:body.policy}));});
app.post("/browser/tasks",async c=>{const body=await c.req.json<any>();const result=await browser.run({id:body.id??crypto.randomUUID(),kind:body.kind??"ask",providerId:body.providerId,objective:body.objective??"",url:body.url,input:body.input,allowedDomains:body.allowedDomains,destructive:Boolean(body.destructive)});return c.json(result,result.ok?200:result.requiresHuman?409:503);});
const host=process.env.MINDZ_GATEWAY_HOST??"127.0.0.1",port=Number(process.env.MINDZ_GATEWAY_PORT??8787);serve({fetch:app.fetch,hostname:host,port});console.log("MIND-Z Gateway listening on http://"+host+":"+port);