import type { WorkflowDefinition } from "@creator-nexus/core";

export const defaultWorkflow: WorkflowDefinition = {
  id: "viral-short-v1",
  name: "Vídeo vertical completo",
  description: "Da ideia à publicação com gates de aprovação humana.",
  version: "1.0.0",
  steps: [
    {
      id: "brief",
      title: "Brief inteligente",
      description: "Clarifica objetivo, público, plataforma, tom e restrições.",
      agent: "Strategist",
      capability: "brief",
      risk: "low",
      requiresApproval: true,
    },
    {
      id: "research",
      title: "Pesquisa & sinais",
      description: "Extrai ângulos, tendências, referências e factos a verificar.",
      agent: "Researcher",
      capability: "research",
      risk: "medium",
      requiresApproval: false,
      minConfidence: 0.78,
      dependsOn: ["brief"],
    },
    {
      id: "script",
      title: "Guião + hooks",
      description: "Produz 3 hooks, corpo, CTA e variações por plataforma.",
      agent: "Writer",
      capability: "script",
      risk: "medium",
      requiresApproval: true,
      dependsOn: ["research"],
    },
    {
      id: "storyboard",
      title: "Storyboard multimodal",
      description: "Divide o guião em cenas, B-roll, overlays, legendas e som.",
      agent: "Director",
      capability: "storyboard",
      risk: "low",
      requiresApproval: false,
      minConfidence: 0.8,
      dependsOn: ["script"],
    },
    {
      id: "render",
      title: "Geração & montagem",
      description: "Orquestra vídeo, avatar, voz, clips, captions e render final.",
      agent: "Producer",
      capability: "render",
      risk: "high",
      requiresApproval: true,
      dependsOn: ["storyboard"],
    },
    {
      id: "qa",
      title: "QA editorial",
      description: "Valida branding, legibilidade, claims, segurança e qualidade.",
      agent: "Reviewer",
      capability: "qa",
      risk: "high",
      requiresApproval: true,
      dependsOn: ["render"],
    },
    {
      id: "publish",
      title: "Publicação",
      description: "Prepara título, descrição, hashtags e agendamento multicanal.",
      agent: "Publisher",
      capability: "publish",
      risk: "critical",
      requiresApproval: true,
      dependsOn: ["qa"],
    },
  ],
};
